### ISSUE TITLE
ERROR Plugin load failed: hexo-next-utteranc Error: Cannot find module 'next-util'

### ISSUE THREAD

**Issue by maixX05** [theme-next/hexo-next-utteranc#6]
ERROR Plugin load failed: hexo-next-utteranc
Error: Cannot find module 'next-util'

**Comment by jiangtj** [comment]
Try `npm i` or `yarn install` to fix module

**Comment by ainy15** [comment]
i also have this problem,and i try `npm i`,but it dosen't work.
the problem as follows
`ERROR Plugin load failed: hexo-next-utteranc
Error: Cannot find module 'C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\next-util\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\hexo\lib\hexo\index.js:280:23)
    at C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\hexo-next-utteranc\index.js:5:14
    at C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\hexo\lib\hexo\index.js:293:14
    at tryCatcher (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\ppap\blog\my\node_modules\bluebird\js\release\promise.js:559:17)
`

**Comment by kands-code** [comment]
Oh, I've tried to use `npm i` to fix it, but it doesn't work for me.

![图片](https://user-images.githubusercontent.com/59006329/108179246-5b631d80-7140-11eb-8f52-7541f78bac1e.png)
